class pocket :
    mysql_host = 'barotestserver.mysql.database.azure.com'      
    mysql_port = 3306
    mysql_user = 'hdh' 
    mysql_password = 'Hyun@@4202'
    mysql_database = 'baro_test_image'
    es_host = 'http://14.45.111.227'
    es_port = 9200
    es_username = 'elastic'
    es_password = '12751275'